### PR TITLE
Update resnet checkpoints 

### PR DESCRIPTION
**Pull request by szatidani**
Update resnet checkpoints based on [PyTorch-Encoding model store](https://github.com/zhanghang1989/PyTorch-Encoding/blob/d9dea1724e38362a7c75ca9498f595248f283f00/encoding/models/model_store.py)
Solves #70

### CODE REVIEW

**Comment by yassouali** [comment]
Thank you !

**Comment by sarath0993** [comment]
These links are also not working now.
`re version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/sarath/anaconda3/envs/pytorchsegth1.1/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/sarath/anaconda3/envs/pytorchsegth1.1/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/sarath/anaconda3/envs/pytorchsegth1.1/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/sarath/anaconda3/envs/pytorchsegth1.1/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/sarath/anaconda3/envs/pytorchsegth1.1/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Downloading: "https://hangzh.s3.amazonaws.com/encoding/models/resnet50s-a75c83cf.zip" to ./pretrained/resnet50s-a75c83cf.zip
Traceback (most recent call last):
  File "train.py", line 61, in <module>
    main(config, args.resume)
  File "train.py", line 26, in main
    model = get_instance(models, 'arch', config, train_loader.dataset.num_classes)
  File "train.py", line 16, in get_instance
    return getattr(module, config[name]['type'])(*args, **config[name]['args'])
  File "/home/sarath/source/pytorch_segmentation/models/pspnet.py", line 46, in __init__
    model = getattr(resnet, backbone)(pretrained, norm_layer=norm_layer, )
  File "/home/sarath/source/pytorch_segmentation/models/resnet.py", line 264, in resnet50
    model.load_state_dict(load_url(model_urls['resnet50'], model_dir=root))
  File "/home/sarath/source/pytorch_segmentation/models/resnet.py", line 300, in load_url
    urlretrieve(url, cached_file)
  File "/home/sarath/anaconda3/envs/pytorchsegth1.1/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/sarath/anaconda3/envs/pytorchsegth1.1/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/sarath/anaconda3/envs/pytorchsegth1.1/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/sarath/anaconda3/envs/pytorchsegth1.1/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/sarath/anaconda3/envs/pytorchsegth1.1/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/sarath/anaconda3/envs/pytorchsegth1.1/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/sarath/anaconda3/envs/pytorchsegth1.1/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
`

**Comment by sarath0993** [comment]
It would be really helpful!! if someone can share a GDRIVE or Dropbox url?? or please send it to my email: sarath0993@gmail.com

**Comment by yassouali** [comment]
Hi, I just updated the links, I think they are working now, I'll also upload them in case the links go down.

**Comment by yassouali** [comment]
the models are here in case the links go down: https://github.com/yassouali/pytorch_segmentation/releases/tag/v0.1
@sarath0993

**Comment by sarath0993** [comment]
@yassouali Thanks a lot! It works great 👯

**Pull request merged**
